export enum JobsStatus {
    CREATING = 'CREATING',
    WAITING_TO_START = 'WAITING_TO_START',
    WAITING_TO_PROCESS = 'WAITING_TO_PROCESS',
    RUNNING = 'RUNNING',
    PAUSED = 'PAUSED',
    PAUSED_BY_SCHEDULE = 'PAUSED_BY_SCHEDULE',
    FINISHED = 'FINISHED',
    ERROR = 'ERROR'
}